### ISSUE TITLE
Order food and post receipt(s) for Muskogee Web Devs event | 2017-06-26

### ISSUE THREAD

**Issue by jsonthebson** [techlahoma/user-groups#178] opened 2017-03-06 12:55 UTC
What: Monthly Meeting
When: 2017-06-26 6:00 PM
Where: 801 W Okmulgee St, Muskogee

Check meetup for RSVP count: https://www.meetup.com/Muskogee-Web-Dev-Design/events/vbxnsmywjbjc/

To requesting reimbursement, please complete the following steps:
- [ ] Picture of receipt(s)
- [ ] Final head count
- [ ] Photo of meetup in action
- [ ] Submit request for reimbursement at https://cash.me/$techlahoma

cc @sgelbart, @ezrinjaz, @lemoney

**Comment by kacollins** [comment] 2017-06-28 12:50
This is a duplicate of #354

**Closed** 2017-06-28 19:49 UTC
Labels: food, reimbursement, UG/Muskogee Web Dev
