### ISSUE TITLE
Arrange food and drink for OKC FP | 2017-07-25

### ISSUE THREAD

**Issue by jsonthebson** [techlahoma/user-groups#383] opened 2017-07-17 20:12 UTC
What: OKC Functional Programming
When: 07/25/2017 11:30 AM
Where: 1141 W Sheridan Ave, Oklahoma City

Check meetup for RSVP count: https://www.meetup.com/OKC-FP/events/241798036/

For @matthewreily:
- [x] Order delivery unless you have written confirmation from a UG leader that they will pick up the order
- [x] Post picture of order here. Please include pickup time and location or delivery time if not included in image

For the UG leadership (@jordan-parmer @alexadriaanse @electricshaman @seejessicacode):
Please follow up with the following:
 - [ ] Picture of receipt(s)
 - [ ] Final head count
 - [ ] Photo of meetup in action
 - [ ] Any food or food service feedback (was it on time, how much was left over, was the service adequate, etc)

**Comment by matthewreily** [comment] 2017-07-25 11:28
Duplicate of #368

**Comment by matthewreily** [comment] 2017-07-25 11:37
![screen shot 2017-07-25 at 6 35 46 am](https://user-images.githubusercontent.com/8399844/28570429-b9a0b83a-7103-11e7-843c-7f1dbd6699f7.png)
![screen shot 2017-07-25 at 6 34 30 am](https://user-images.githubusercontent.com/8399844/28570430-bb05d624-7103-11e7-9fad-e02aa98c4cd4.png)

**Comment by jordan-parmer** [comment] 2017-07-25 17:00
18 attendees in person with 4 online at peak

**Comment by seejessicacode** [comment] 2017-07-25 17:18
Got a receipt?

**Comment by alexadriaanse** [comment] 2017-07-25 17:20
Final head count: 18 (+ 7 max. stream viewers)

Food was on time, amount of pizza was perfect (there was about a half box of pizza left over).

![okc fp 2017-07-25 receipt](https://user-images.githubusercontent.com/2073254/28584034-da7798ee-7130-11e7-85b6-448ac15798cf.jpg)

![okc fp 2017-07-25 photo](https://user-images.githubusercontent.com/2073254/28584035-da8e69ca-7130-11e7-8342-e81035b06fc6.jpg)

**Comment by seejessicacode** [comment] 2017-07-25 17:31
Thanks!!

**Closed by seejessicacode** 2017-07-25 17:31 UTC
Labels: food, UG/OKC FP
