### ISSUE TITLE
Request reimbursement for food and drink forTulsa Web Devs event | 2019-04-02

### ISSUE THREAD

**Issue by jsonthebson** [techlahoma/user-groups#802] opened 2018-03-21 14:05 UTC
What: Techlahoma Hack Night
When: 2019-04-02 6:00 PM
Where: 36 East Cameron St., Tulsa

Check meetup for RSVP count: https://www.meetup.com/Tulsa-Web-Devs/events/qjqkbmyzgbdb/

To request reimbursement, please complete the following steps:
- [ ] Post picture of receipt(s) in this thread
- [ ] Post photo(s) of the meetup in action on your meetup event
- [ ] Submit [request for reimbursement](https://github.com/techlahoma/user-groups/wiki/Requesting-Reimbursement) from $techlahoma on https://cash.me within 1 month of the event

Any questions about reimbursement may be referred to the board treasurer.

cc @jdungan, @groovecoder

**Comment by kacollins** [comment] 2018-06-16 15:41
Duplicate of #945

**Closed by kacollins** 2018-06-16 15:41 UTC
Labels: UG/Tulsa Web Devs, food, reimbursement
