### ISSUE TITLE
Request reimbursement for food and drink for OKC.js | 2018-02-20

### ISSUE THREAD

**Issue by jsonthebson** [techlahoma/user-groups#725] opened 2018-01-29 16:46 UTC
What: Double Feature: Pong in Native JS with Aaron Krauss/Babylon.js with Jesse Harlin
When: 02/20/2018 11:30 am
Where: 1141 W Sheridan Ave, Oklahoma City

Check meetup for RSVP count: https://www.meetup.com/OKC-js/events/247259379/

To request reimbursement, please complete the following steps:
- [ ] Post picture of receipt(s) in this thread
- [ ] Post photo(s) of the meetup in action on your meetup event
- [ ] Submit [request for reimbursement](https://github.com/techlahoma/user-groups/wiki/Requesting-Reimbursement) from $techlahoma on https://cash.me within 1 month of the event

Any questions about reimbursement may be referred to the board treasurer.

cc @the-simian @amandaharlin @vlucas

**Comment by seejessicacode** [comment] 2018-01-29 17:51
duplicate of #723

**Closed by seejessicacode** 2018-01-29 17:51 UTC
Labels: UG/OKC JS, food, reimbursement
