### ISSUE TITLE
Request reimbursement for food and drink for Big Data and Data Science in OKC event | 2018-02-01

### ISSUE THREAD

**Issue by jsonthebson** [techlahoma/user-groups#726] opened 2018-01-29 17:14 UTC
What: Data Pipelines. Structured Streaming. Move you data continously near real time.
When: 08/03/2017 12:30 pm
Where: 1141 W Sheridan Ave, Oklahoma City

Check meetup for RSVP count: https://www.meetup.com/Big-Data-in-Oklahoma-City/events/246913444/

To request reimbursement, please complete the following steps:
- [ ] Post picture of receipt(s) in this thread
- [ ] Post photo(s) of the meetup in action on your meetup event
- [ ] Submit [request for reimbursement](https://github.com/techlahoma/user-groups/wiki/Requesting-Reimbursement) from $techlahoma on https://cash.me within 1 month of the event

Any questions about reimbursement may be referred to the board treasurer.

cc @max522over @matthewreily

**Comment by seejessicacode** [comment] 2018-01-29 17:50
duplicate of #671

**Closed by seejessicacode** 2018-01-29 17:50 UTC
Labels: UG/Big Data in OKC, food, reimbursement
