### ISSUE TITLE
Existing User Group Submission: Tulsa Game Developers - TGD

### ISSUE THREAD

**Issue by jsonthebson** [techlahoma/user-groups#52] opened 2016-12-15 22:17 UTC
**Agree to CoC:** Yes
**Group name:** Tulsa Game Developers - TGD
**Purpose:** 
**Current location:** 36° North 
**Current meeting date and time:** Every third Thursday
**Leadership:** Richard Mitchell - Group Lead
Tyler Woodall
**Avg. # of attendees:** 15-20 per month
**Avg. cost per meeting:** $80
**Twitter:** tulsagamedevs
**Website:** http://tulsagamedevs.tumblr.com
**Would like help with:** Funding for Food & Drink, Social Media / Announcement, Connecting to the greater OK communtiy

Submitted by Richard Mitchell on 12/15/2016 16:14:54

**Comment by groovecoder** [comment] 2016-12-16 02:00
Is this a dupe of #30?

**Comment by amandaharlin** [comment] 2016-12-16 04:07
looks like it, imo

**Comment by groovecoder** [comment] 2016-12-16 04:10
This one is more thorough, so I'll close the other one.

**Comment by seejessicacode** [comment] 2016-12-22 00:58
Approved! Will close issue after following up with UG leader(s).

https://github.com/techlahoma/board_meetings/blob/master/2016/12_december-minutes.md

**Comment by seejessicacode** [comment] 2017-01-09 14:40
Approval email sent.

**Comment by seejessicacode** [comment] 2017-01-17 18:21
- [ ] Add to http://www.techlahoma.org/usergroups/
- [ ] Add to https://www.meetup.com/pro/techlahoma/
- [ ] Set up automation for announcements and GH issues

**Closed** 2017-01-19 02:52 UTC
Labels: on boarding, User Group Application
