### ISSUE TITLE
Arrange food and drink for OKC JUG event | 2017-08-08

### ISSUE THREAD

**Issue by jsonthebson** [techlahoma/user-groups#391] opened 2017-07-26 19:57 UTC
What: Lions And Tigers And GraphQL (Oh My)
When: 08/08/2017 11:30 am
Where: 1141 W Sheridan Ave, Oklahoma City

Check meetup for RSVP count: https://www.meetup.com/okcjug/events/242040998/

For @matthewreily:
- [ ] Order delivery unless you have written confirmation from a UG leader that they will pick up the order
- [ ] Post picture of order here. Please include pickup time and location or delivery time if not included in image

For the UG leadership (@rhoegg, @jasondlee):
Please follow up with the following:
 - [ ] Picture of receipt(s)
 - [ ] Final head count
 - [ ] Photo of meetup in action
 - [ ] Any food or food service feedback (was it on time, how much was left over, was the service adequate, etc)

**Comment by rhoegg** [comment] 2017-08-08 16:40
Hi this looks like a duplicate of #393

**Closed** 2017-08-08 17:16 UTC
Labels: food, UG/OKC JUG
