### ISSUE TITLE
Request reimbursement for food and drink forTulsa Web Devs event | 2018-08-07

### ISSUE THREAD

**Issue by jsonthebson** [techlahoma/user-groups#938] opened 2018-06-07 04:30 UTC
What: Techlahoma Hack Night
When: 2018-08-07 6:00 PM
Where: 36 East Cameron St., Tulsa

Check meetup for RSVP count: https://www.meetup.com/Tulsa-Web-Devs/events/nnqstpyxlbkb/

To request reimbursement, please complete the following steps:
- [ ] Post picture of receipt(s) in this thread
- [ ] Post photo(s) of the meetup in action on your meetup event
- [ ] Submit [request for reimbursement](https://github.com/techlahoma/user-groups/wiki/Requesting-Reimbursement) from $techlahoma on https://venmo.com within 1 month of the event

Any questions about reimbursement may be referred to the board treasurer.

cc @jdungan, @groovecoder

**Comment by kendallcorner** [comment] 2018-08-08 15:15
@chimchim, @kacollins this one is the duplicate.

**Comment by kacollins** [comment] 2018-08-08 15:55
Any idea what is causing the duplicates?

**Comment by kacollins** [comment] 2018-08-09 10:53
I wasn't able to find a duplicate of this one. When you find a duplicate, can you please [mark it](https://help.github.com/articles/about-duplicate-issues-and-pull-requests/) as "duplicate of" the original issue number? That will help me track down what is causing the problem.

**Comment by kendallcorner** [comment] 2018-08-09 21:25
Duplicate of #1081

**Comment by kendallcorner** [comment] 2018-08-09 21:26
It's happening, because @groovecoder and @chimchim that these are auto-created and that you don't have to make a new one ;-)

**Comment by kacollins** [comment] 2018-08-10 12:36
This might help for finding the issues: https://kacollins.github.io/issue-sorter/

I can also tag @chimchim in the Tulsa Web Devs events. Please let me know if you're not able to find a generated issue, because it could be a problem with our automation.

**Comment by kendallcorner** [comment] 2018-08-10 14:10
It's happening, because @groovecoder and @chimchim didn't know that these are auto-created and that you don't have to make a new one ;-)

**Closed** 2018-08-11 02:38 UTC
Labels: UG/Tulsa Web Devs, food, reimbursement
