### ISSUE TITLE
Arrange food and drink for OKC FP | 2017-09-26

### ISSUE THREAD

**Issue by jsonthebson** [techlahoma/user-groups#368] opened 2017-06-30 13:37 UTC
What: OKC Functional Programming
When: 09/26/2017 11:30 AM
Where: 1141 W Sheridan Ave, Oklahoma City

Check meetup for RSVP count: https://www.meetup.com/OKC-FP/events/241200493/

For @matthewreily:
- [x] Order delivery unless you have written confirmation from a UG leader that they will pick up the order
- [x] Post picture of order here. Please include pickup time and location or delivery time if not included in image

For the UG leadership (@jordan-parmer @alexadriaanse @electricshaman @seejessicacode):
Please follow up with the following:
 - [x] Picture of receipt(s)
 - [x] Final head count
 - [x] Photo of meetup in action
 - [x] Any food or food service feedback (was it on time, how much was left over, was the service adequate, etc)

**Comment by matthewreily** [comment] 2017-07-25 11:41
@jordan-parmer can you verify this is the correct date?  The issue first appeared to be a duplicate of today's 7/25 meetup but the link inside the issue was for September.

**Comment by jordan-parmer** [comment] 2017-07-25 12:22
@matthewreily Yes, it's correct. The meet-up is today. We had a shift in speaker dates so what I did was change the MeetUp time of the original meeting and create a new one for this month.

**Comment by kacollins** [comment] 2017-07-25 13:37
Should the title of this one be changed to 2017-09-26 to avoid confusion with the issue for today?

**Comment by kacollins** [comment] 2017-07-25 15:55
I went ahead and changed the title to correct the date. I would have hated for the September meetup to not have food because of this.

**Comment by jordan-parmer** [comment] 2017-07-25 17:00
@kacollins where is the ticket for today's meet-up?

**Comment by matthewreily** [comment] 2017-09-26 15:12
<img width="888" alt="screen shot 2017-09-26 at 10 08 49 am" src="https://user-images.githubusercontent.com/8399844/30868019-1da66598-a2a3-11e7-87b7-1e7904bdc054.png">

**Comment by jordan-parmer** [comment] 2017-09-26 18:08
![img_20170926_113537](https://user-images.githubusercontent.com/5378348/30876297-cd67ca9a-a2bb-11e7-8ef5-7c203477d490.jpg)

**Comment by jordan-parmer** [comment] 2017-09-26 18:09
26 people in-house and 10 people online. Perfect amount of pizza - only one slice left!

**Comment by jordan-parmer** [comment] 2017-09-26 18:10
![img_20170926_114828](https://user-images.githubusercontent.com/5378348/30876376-11aab316-a2bc-11e7-85cf-6db50cb108fc.jpg)
![img_20170926_114807](https://user-images.githubusercontent.com/5378348/30876377-11ac0392-a2bc-11e7-80c3-77aafabae112.jpg)

**Closed** 2017-10-02 01:38 UTC
Labels: food, UG/OKC FP
